# Locked Users Monitor (Standalone)

[CmdletBinding()]
param()

# Load assemblies
Add-Type -AssemblyName System.Windows.Forms
Add-Type -AssemblyName System.Drawing

$script:isRefreshing = $false

# Resolve paths
$scriptRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
$appRoot = Split-Path -Parent $scriptRoot
$modulesPath = Join-Path $appRoot 'Modules'
# Prefer a dedicated icon for the monitor; fall back to ADapp icon if not present
$iconPath = Join-Path $appRoot 'assets\icons\LockedMonitor.ico'
if (-not (Test-Path $iconPath)) { $iconPath = Join-Path $appRoot 'assets\icons\adapp.ico' }

# Ensure proper taskbar icon by setting an explicit AppUserModelID (prevents default PowerShell icon)
try {
    if (-not ([type]::GetType('WinAPI.TaskbarHelper'))) {
        Add-Type -AssemblyName System.Runtime.InteropServices
        Add-Type -TypeDefinition @"
using System;
using System.Runtime.InteropServices;
namespace WinAPI {
  public static class TaskbarHelper {
    [DllImport("shell32.dll", SetLastError = true)]
    public static extern void SetCurrentProcessExplicitAppUserModelID([MarshalAs(UnmanagedType.LPWStr)] string AppID);
  }
}
"@ -Language CSharp
    }
    [WinAPI.TaskbarHelper]::SetCurrentProcessExplicitAppUserModelID("LockedUsersMonitor")
} catch {}

# Data folder
$monitorDataDir = Join-Path $env:ProgramData 'ADapp\Monitor'
if (-not (Test-Path $monitorDataDir)) { New-Item -ItemType Directory -Path $monitorDataDir -Force | Out-Null }
$eventsPath = Join-Path $monitorDataDir 'lockout-events.json'
$statePath  = Join-Path $monitorDataDir 'state.json'

<#
.SYNOPSIS
Brief description of Write-UiStatus.
.DESCRIPTION
Extended description of Write-UiStatus.
.PARAMETER text
Description.
.INPUTS
None
.OUTPUTS
None
.EXAMPLE
Write-UiStatus -text <value>
.NOTES
Auto-generated by tools/Add-HelpStubs.ps1. Please refine as needed.
#>

function Write-UiStatus([string]$text) {
    if ($null -ne $statusLabel) { $statusLabel.Text = $text }
}

<#
.SYNOPSIS
Brief description of Load-ModuleSafe.
.DESCRIPTION
Extended description of Load-ModuleSafe.

.INPUTS
None
.OUTPUTS
None
.EXAMPLE
Load-ModuleSafe
.NOTES
Auto-generated by tools/Add-HelpStubs.ps1. Please refine as needed.
#>

function Load-ModuleSafe {
    try { Import-Module ActiveDirectory -ErrorAction Stop } catch {
        [System.Windows.Forms.MessageBox]::Show("ActiveDirectory module not found: $_", "Locked Monitor", [System.Windows.Forms.MessageBoxButtons]::OK, [System.Windows.Forms.MessageBoxIcon]::Error) | Out-Null
        exit 1
    }
    try { Import-Module (Join-Path $modulesPath 'LockedAccounts.psm1') -Force -DisableNameChecking -ErrorAction Stop } catch {
        [System.Windows.Forms.MessageBox]::Show("LockedAccounts module not found: $_", "Locked Monitor", [System.Windows.Forms.MessageBoxButtons]::OK, [System.Windows.Forms.MessageBoxIcon]::Error) | Out-Null
        exit 1
    }
}

<#
.SYNOPSIS
Brief description of Load-Events.
.DESCRIPTION
Extended description of Load-Events.

.INPUTS
None
.OUTPUTS
None
.EXAMPLE
Load-Events
.NOTES
Auto-generated by tools/Add-HelpStubs.ps1. Please refine as needed.
#>

function Load-Events {
    if (Test-Path $eventsPath) {
        try { return (Get-Content $eventsPath -Raw | ConvertFrom-Json) } catch { return @() }
    }
    return @()
}

<#
.SYNOPSIS
Brief description of Save-Events.
.DESCRIPTION
Extended description of Save-Events.
.PARAMETER events
Description.
.INPUTS
None
.OUTPUTS
None
.EXAMPLE
Save-Events -events <value>
.NOTES
Auto-generated by tools/Add-HelpStubs.ps1. Please refine as needed.
#>

function Save-Events([object[]]$events) {
    try { $events | ConvertTo-Json -Depth 5 | Set-Content -Path $eventsPath -Encoding UTF8 } catch {}
}

<#
.SYNOPSIS
Brief description of Prune-Events.
.DESCRIPTION
Extended description of Prune-Events.
.PARAMETER events
Description.
.PARAMETER retain
Description.
.INPUTS
None
.OUTPUTS
None
.EXAMPLE
Prune-Events -events <value> -retain <value>
.NOTES
Auto-generated by tools/Add-HelpStubs.ps1. Please refine as needed.
#>

function Prune-Events([object[]]$events, [TimeSpan]$retain) {
    $cutoff = (Get-Date).Add(-$retain)
    return @($events | Where-Object { try { [datetime]$_.Timestamp -ge $cutoff } catch { $false } })
}

<#
.SYNOPSIS
Brief description of Load-State.
.DESCRIPTION
Extended description of Load-State.

.INPUTS
None
.OUTPUTS
None
.EXAMPLE
Load-State
.NOTES
Auto-generated by tools/Add-HelpStubs.ps1. Please refine as needed.
#>

function Load-State {
    if (Test-Path $statePath) {
        try { return (Get-Content $statePath -Raw | ConvertFrom-Json) } catch { return [pscustomobject]@{ LastLocked = @(); LastRefresh = $null } }
    }
    return [pscustomobject]@{ LastLocked = @(); LastRefresh = $null }
}

<#
.SYNOPSIS
Brief description of Save-State.
.DESCRIPTION
Extended description of Save-State.
.PARAMETER state
Description.
.INPUTS
None
.OUTPUTS
None
.EXAMPLE
Save-State -state <value>
.NOTES
Auto-generated by tools/Add-HelpStubs.ps1. Please refine as needed.
#>

function Save-State($state) {
    try { $state | ConvertTo-Json -Depth 5 | Set-Content -Path $statePath -Encoding UTF8 } catch {}
}

<#
.SYNOPSIS
Brief description of Get-SelectedRangeSpan.
.DESCRIPTION
Extended description of Get-SelectedRangeSpan.

.INPUTS
None
.OUTPUTS
None
.EXAMPLE
Get-SelectedRangeSpan
.NOTES
Auto-generated by tools/Add-HelpStubs.ps1. Please refine as needed.
#>

function Get-SelectedRangeSpan {
    switch ($rangeCombo.SelectedItem) {
        '1h' { return [TimeSpan]::FromHours(1) }
        '4h' { return [TimeSpan]::FromHours(4) }
        '12h' { return [TimeSpan]::FromHours(12) }
        '24h' { return [TimeSpan]::FromHours(24) }
        '7d' { return [TimeSpan]::FromDays(7) }
        '30d' { return [TimeSpan]::FromDays(30) }
        default { return $null }
    }
}

<#
.SYNOPSIS
Brief description of Get-IntervalMs.
.DESCRIPTION
Extended description of Get-IntervalMs.

.INPUTS
None
.OUTPUTS
None
.EXAMPLE
Get-IntervalMs
.NOTES
Auto-generated by tools/Add-HelpStubs.ps1. Please refine as needed.
#>

function Get-IntervalMs {
    switch ($intervalCombo.SelectedItem) {
        '15s' { 15000 }
        '30s' { 30000 }
        '1m'  { 60000 }
        '2m'  { 120000 }
        '5m'  { 300000 }
        default { 30000 }
    }
}

<#
.SYNOPSIS
Brief description of Ensure-ControlsEnabled.
.DESCRIPTION
Extended description of Ensure-ControlsEnabled.
.PARAMETER enabled
Description.
.INPUTS
None
.OUTPUTS
None
.EXAMPLE
Ensure-ControlsEnabled -enabled <value>
.NOTES
Auto-generated by tools/Add-HelpStubs.ps1. Please refine as needed.
#>

function Ensure-ControlsEnabled([bool]$enabled) {
    $refreshButton.Enabled = $enabled
    $autoRefreshCheck.Enabled = $enabled
    $intervalCombo.Enabled = $enabled -and $autoRefreshCheck.Checked
    $rangeCombo.Enabled = $enabled
    $fromPicker.Enabled = $enabled -and ($rangeCombo.SelectedItem -eq 'Custom')
    $toPicker.Enabled = $enabled -and ($rangeCombo.SelectedItem -eq 'Custom')
    $unlockButton.Enabled = $enabled -and ($listView.SelectedItems.Count -gt 0)
    $resetButton.Enabled = $enabled -and ($listView.SelectedItems.Count -gt 0)
}

<#
.SYNOPSIS
Brief description of Get-CurrentLockedUsers.
.DESCRIPTION
Extended description of Get-CurrentLockedUsers.

.INPUTS
None
.OUTPUTS
None
.EXAMPLE
Get-CurrentLockedUsers
.NOTES
Auto-generated by tools/Add-HelpStubs.ps1. Please refine as needed.
#>

function Get-CurrentLockedUsers {
    $users = Get-LockedADAccounts
    if ($null -eq $users) { return @() }
    return @($users)
}

<#
.SYNOPSIS
Brief description of Compute-LockoutCounts.
.DESCRIPTION
Extended description of Compute-LockoutCounts.
.PARAMETER events
Description.
.PARAMETER from
Description.
.PARAMETER to
Description.
.INPUTS
None
.OUTPUTS
None
.EXAMPLE
Compute-LockoutCounts -events <value> -from <value> -to <value>
.NOTES
Auto-generated by tools/Add-HelpStubs.ps1. Please refine as needed.
#>

function Compute-LockoutCounts([object[]]$events, [DateTime]$from, [DateTime]$to) {
    $counts = @{}
    foreach ($e in $events) {
        try {
            $ts = [datetime]$e.Timestamp
            if ($ts -ge $from -and $ts -le $to) {
                $u = [string]$e.Username
                if (-not $counts.ContainsKey($u)) { $counts[$u] = 0 }
                $counts[$u]++
            }
        } catch {}
    }
    return $counts
}

<#
.SYNOPSIS
Brief description of Update-ListView.
.DESCRIPTION
Extended description of Update-ListView.
.PARAMETER currentUsers
Description.
.PARAMETER counts
Description.
.INPUTS
None
.OUTPUTS
None
.EXAMPLE
Update-ListView -currentUsers <value> -counts <value>
.NOTES
Auto-generated by tools/Add-HelpStubs.ps1. Please refine as needed.
#>

function Update-ListView([object[]]$currentUsers, [hashtable]$counts) {
    $listView.BeginUpdate()
    $listView.Items.Clear()
    foreach ($u in $currentUsers) {
        $username = $u.SamAccountName
        $fullName = ("{0} {1}" -f $u.GivenName, $u.Surname).Trim()
        $title = $u.Title
        $lastLogon = if ($u.LastLogon) { [datetime]::FromFileTime($u.LastLogon).ToString('g') } else { 'Never' }
        $count = if ($counts.ContainsKey($username)) { $counts[$username] } else { 0 }

        $item = New-Object System.Windows.Forms.ListViewItem($username)
        $null = $item.SubItems.Add($fullName)
        $null = $item.SubItems.Add($title)
        $null = $item.SubItems.Add($lastLogon)
        $null = $item.SubItems.Add([string]$count)
        $item.Tag = $username
        $listView.Items.Add($item) | Out-Null
    }
    $listView.EndUpdate()
    Write-UiStatus ("Showing {0} locked accounts | Last refresh: {1}" -f $currentUsers.Count, (Get-Date).ToString('yyyy-MM-dd HH:mm:ss'))
}

<#
.SYNOPSIS
Brief description of Record-NewLockouts.
.DESCRIPTION
Extended description of Record-NewLockouts.
.PARAMETER prevLocked
Description.
.PARAMETER currLocked
Description.
.INPUTS
None
.OUTPUTS
None
.EXAMPLE
Record-NewLockouts -prevLocked <value> -currLocked <value>
.NOTES
Auto-generated by tools/Add-HelpStubs.ps1. Please refine as needed.
#>

function Record-NewLockouts([string[]]$prevLocked, [string[]]$currLocked) {
    $prevSet = [System.Collections.Generic.HashSet[string]]::new($prevLocked)
    $newlyLocked = @($currLocked | Where-Object { -not $prevSet.Contains($_) })
    if (-not $newlyLocked.Count) { return }
    $events = Load-Events
    $now = Get-Date
    foreach ($n in $newlyLocked) {
        $events += [pscustomobject]@{ Timestamp = $now; Username = $n }
    }
    Save-Events -events $events
}

<#
.SYNOPSIS
Brief description of Do-Refresh.
.DESCRIPTION
Extended description of Do-Refresh.

.INPUTS
None
.OUTPUTS
None
.EXAMPLE
Do-Refresh
.NOTES
Auto-generated by tools/Add-HelpStubs.ps1. Please refine as needed.
#>

function Do-Refresh {
    if ($script:isRefreshing) { return }
    $script:isRefreshing = $true
    Ensure-ControlsEnabled $false
    Write-UiStatus 'Refreshing...'
    try {
        $state = Load-State
        $prevLocked = @($state.LastLocked)
        $users = Get-CurrentLockedUsers
        $currLocked = @($users | ForEach-Object { $_.SamAccountName })

        if (-not $state.LastRefresh) {
            # First run: set baseline to avoid counting initial set as events
            $state.LastLocked = $currLocked
            $state.LastRefresh = Get-Date
            Save-State -state $state
        } else {
            Record-NewLockouts -prevLocked $prevLocked -currLocked $currLocked
            $state.LastLocked = $currLocked
            $state.LastRefresh = Get-Date
            Save-State -state $state
        }

        # Determine display window
        if ($rangeCombo.SelectedItem -eq 'Custom') {
            $from = $fromPicker.Value
            $to = $toPicker.Value
        } else {
            $span = Get-SelectedRangeSpan
            $to = Get-Date
            $from = $to.Add(-$span)
        }
        $events = Load-Events
        $counts = Compute-LockoutCounts -events $events -from $from -to $to
        Update-ListView -currentUsers $users -counts $counts
    } catch {
        [System.Windows.Forms.MessageBox]::Show("Refresh failed: $_", "Locked Monitor", [System.Windows.Forms.MessageBoxButtons]::OK, [System.Windows.Forms.MessageBoxIcon]::Error) | Out-Null
    } finally {
        Ensure-ControlsEnabled $true
        $script:isRefreshing = $false
    }
}

<#
.SYNOPSIS
Brief description of Unlock-Selected.
.DESCRIPTION
Extended description of Unlock-Selected.

.INPUTS
None
.OUTPUTS
None
.EXAMPLE
Unlock-Selected
.NOTES
Auto-generated by tools/Add-HelpStubs.ps1. Please refine as needed.
#>

function Unlock-Selected {
    if ($listView.SelectedItems.Count -eq 0) { return }
    $ids = @($listView.SelectedItems | ForEach-Object { $_.Text })
    foreach ($id in $ids) {
        $r = Unlock-ADUserAccount -Identity $id | Select-Object -First 1
        if (-not $r.Unlocked) {
            [System.Windows.Forms.MessageBox]::Show("Failed to unlock ${id}: $($r.Error)", "Unlock", [System.Windows.Forms.MessageBoxButtons]::OK, [System.Windows.Forms.MessageBoxIcon]::Error) | Out-Null
        }
    }
    Do-Refresh
}

<#
.SYNOPSIS
Brief description of Show-PasswordDialog.
.DESCRIPTION
Extended description of Show-PasswordDialog.

.INPUTS
None
.OUTPUTS
None
.EXAMPLE
Show-PasswordDialog
.NOTES
Auto-generated by tools/Add-HelpStubs.ps1. Please refine as needed.
#>

function Show-PasswordDialog {
    $dlg = New-Object System.Windows.Forms.Form
    $dlg.Text = 'Reset Password'
    $dlg.Size = New-Object System.Drawing.Size(360, 200)
    $dlg.StartPosition = 'CenterParent'
    $dlg.FormBorderStyle = [System.Windows.Forms.FormBorderStyle]::FixedDialog
    $dlg.MaximizeBox = $false; $dlg.MinimizeBox = $false

    $lbl1 = New-Object System.Windows.Forms.Label; $lbl1.Text = 'New password:'; $lbl1.Location = '10,20'; $lbl1.AutoSize = $true
    $txt1 = New-Object System.Windows.Forms.TextBox; $txt1.Location = '140,18'; $txt1.Size = '190,20'; $txt1.UseSystemPasswordChar = $true
    $lbl2 = New-Object System.Windows.Forms.Label; $lbl2.Text = 'Confirm password:'; $lbl2.Location = '10,55'; $lbl2.AutoSize = $true
    $txt2 = New-Object System.Windows.Forms.TextBox; $txt2.Location = '140,53'; $txt2.Size = '190,20'; $txt2.UseSystemPasswordChar = $true
    $chk = New-Object System.Windows.Forms.CheckBox; $chk.Text = 'Require change at next logon'; $chk.Location = '10,85'; $chk.AutoSize = $true; $chk.Checked = $true
    $ok = New-Object System.Windows.Forms.Button; $ok.Text = 'OK'; $ok.Location = '175,120'; $ok.DialogResult = [System.Windows.Forms.DialogResult]::OK
    $cancel = New-Object System.Windows.Forms.Button; $cancel.Text = 'Cancel'; $cancel.Location = '255,120'; $cancel.DialogResult = [System.Windows.Forms.DialogResult]::Cancel

    $dlg.Controls.AddRange(@($lbl1,$txt1,$lbl2,$txt2,$chk,$ok,$cancel))
    $dlg.AcceptButton = $ok; $dlg.CancelButton = $cancel
    $res = $dlg.ShowDialog()
    if ($res -ne [System.Windows.Forms.DialogResult]::OK) { return $null }
    if ([string]::IsNullOrWhiteSpace($txt1.Text) -or $txt1.Text -ne $txt2.Text) {
        [System.Windows.Forms.MessageBox]::Show('Passwords do not match or are empty.','Reset Password',[System.Windows.Forms.MessageBoxButtons]::OK,[System.Windows.Forms.MessageBoxIcon]::Warning) | Out-Null
        return $null
    }
    return @{ Password = $txt1.Text; RequireChange = $chk.Checked }
}

<#
.SYNOPSIS
Brief description of Reset-SelectedPassword.
.DESCRIPTION
Extended description of Reset-SelectedPassword.

.INPUTS
None
.OUTPUTS
None
.EXAMPLE
Reset-SelectedPassword
.NOTES
Auto-generated by tools/Add-HelpStubs.ps1. Please refine as needed.
#>

function Reset-SelectedPassword {
    if ($listView.SelectedItems.Count -eq 0) { return }
    $username = $listView.SelectedItems[0].Text
    $dlgRes = Show-PasswordDialog
    if ($null -eq $dlgRes) { return }
    
    # Validate password complexity
    if (Get-Command Test-PasswordComplexity -ErrorAction SilentlyContinue) {
        $validation = Test-PasswordComplexity -Password $dlgRes.Password
        if (-not $validation.IsValid) {
            [System.Windows.Forms.MessageBox]::Show($validation.ErrorMessage, "Password Complexity Error", [System.Windows.Forms.MessageBoxButtons]::OK, [System.Windows.Forms.MessageBoxIcon]::Error) | Out-Null
            return
        }
    }
    
    $sec = ConvertTo-SecureString -String $dlgRes.Password -AsPlainText -Force
    $r = Reset-ADUserPassword -Identity $username -NewPassword $sec -PlainTextPassword $dlgRes.Password -RequireChangeAtNextLogon:([bool]$dlgRes.RequireChange)
    if (-not $r.Reset) {
        [System.Windows.Forms.MessageBox]::Show("Failed to reset password for ${username}: $($r.Error)", "Reset Password", [System.Windows.Forms.MessageBoxButtons]::OK, [System.Windows.Forms.MessageBoxIcon]::Error) | Out-Null
    } else {
        [System.Windows.Forms.MessageBox]::Show("Password reset successful for ${username}.", "Reset Password", [System.Windows.Forms.MessageBoxButtons]::OK, [System.Windows.Forms.MessageBoxIcon]::Information) | Out-Null
    }
}

<#
.SYNOPSIS
Brief description of Initialize-UI.
.DESCRIPTION
Extended description of Initialize-UI.

.INPUTS
None
.OUTPUTS
None
.EXAMPLE
Initialize-UI
.NOTES
Auto-generated by tools/Add-HelpStubs.ps1. Please refine as needed.
#>

function Initialize-UI {
    $form = New-Object System.Windows.Forms.Form
    $form.Text = 'Locked Accounts Monitor'
    $form.Size = New-Object System.Drawing.Size(900, 600)
    $form.StartPosition = 'CenterScreen'
    if (Test-Path $iconPath) { try { $form.Icon = [System.Drawing.Icon]::new($iconPath) } catch {} }

    # Top panel
    $top = New-Object System.Windows.Forms.Panel
    $top.Dock = [System.Windows.Forms.DockStyle]::Top
    $top.Height = 42
    $form.Controls.Add($top)

    $refreshButton = New-Object System.Windows.Forms.Button
    $refreshButton.Text = 'Refresh'
    $refreshButton.Location = New-Object System.Drawing.Point(10, 9)
    $refreshButton.Size = New-Object System.Drawing.Size(75, 24)
    $top.Controls.Add($refreshButton)

    $autoRefreshCheck = New-Object System.Windows.Forms.CheckBox
    $autoRefreshCheck.Text = 'Auto-refresh'
    $autoRefreshCheck.Location = New-Object System.Drawing.Point(100, 12)
    $autoRefreshCheck.AutoSize = $true
    $top.Controls.Add($autoRefreshCheck)

    $intervalCombo = New-Object System.Windows.Forms.ComboBox
    $intervalCombo.DropDownStyle = 'DropDownList'
    $intervalCombo.Items.AddRange(@('15s','30s','1m','2m','5m'))
    $intervalCombo.SelectedIndex = 1 # 30s
    $intervalCombo.Location = New-Object System.Drawing.Point(200, 10)
    $intervalCombo.Width = 70
    $top.Controls.Add($intervalCombo)

    $rangeLabel = New-Object System.Windows.Forms.Label
    $rangeLabel.Text = 'Range:'
    $rangeLabel.AutoSize = $true
    $rangeLabel.Location = New-Object System.Drawing.Point(290, 14)
    $top.Controls.Add($rangeLabel)

    $rangeCombo = New-Object System.Windows.Forms.ComboBox
    $rangeCombo.DropDownStyle = 'DropDownList'
    $rangeCombo.Items.AddRange(@('1h','4h','12h','24h','7d','30d','Custom'))
    $rangeCombo.SelectedIndex = 3 # 24h
    $rangeCombo.Location = New-Object System.Drawing.Point(340, 10)
    $rangeCombo.Width = 80
    $top.Controls.Add($rangeCombo)

    $fromPicker = New-Object System.Windows.Forms.DateTimePicker
    $fromPicker.Format = [System.Windows.Forms.DateTimePickerFormat]::Custom
    $fromPicker.CustomFormat = 'yyyy-MM-dd HH:mm'
    $fromPicker.Location = New-Object System.Drawing.Point(430, 10)
    $fromPicker.Width = 150
    $fromPicker.Enabled = $false
    $top.Controls.Add($fromPicker)

    $toPicker = New-Object System.Windows.Forms.DateTimePicker
    $toPicker.Format = [System.Windows.Forms.DateTimePickerFormat]::Custom
    $toPicker.CustomFormat = 'yyyy-MM-dd HH:mm'
    $toPicker.Location = New-Object System.Drawing.Point(590, 10)
    $toPicker.Width = 150
    $toPicker.Enabled = $false
    $top.Controls.Add($toPicker)

    # ListView
    $listView = New-Object System.Windows.Forms.ListView
    $listView.Dock = [System.Windows.Forms.DockStyle]::Fill
    $listView.View = [System.Windows.Forms.View]::Details
    $listView.FullRowSelect = $true
    $listView.GridLines = $true
    $listView.Columns.Add('Username', 140) | Out-Null
    $listView.Columns.Add('Full Name', 180) | Out-Null
    $listView.Columns.Add('Title', 160) | Out-Null
    $listView.Columns.Add('Last Logon', 140) | Out-Null
    $listView.Columns.Add('Lockouts', 80) | Out-Null
    $form.Controls.Add($listView)
    $listView.BringToFront()

    # Bottom panel
    $bottom = New-Object System.Windows.Forms.Panel
    $bottom.Dock = [System.Windows.Forms.DockStyle]::Bottom
    $bottom.Height = 36
    $form.Controls.Add($bottom)

    $unlockButton = New-Object System.Windows.Forms.Button
    $unlockButton.Text = 'Unlock Selected'
    $unlockButton.Location = New-Object System.Drawing.Point(10, 6)
    $unlockButton.Size = New-Object System.Drawing.Size(120, 24)
    $bottom.Controls.Add($unlockButton)

    $resetButton = New-Object System.Windows.Forms.Button
    $resetButton.Text = 'Reset Password...'
    $resetButton.Location = New-Object System.Drawing.Point(140, 6)
    $resetButton.Size = New-Object System.Drawing.Size(130, 24)
    $bottom.Controls.Add($resetButton)

    $statusLabel = New-Object System.Windows.Forms.Label
    $statusLabel.Text = 'Ready'
    $statusLabel.AutoSize = $true
    $statusLabel.Location = New-Object System.Drawing.Point(290, 10)
    $bottom.Controls.Add($statusLabel)

    # Timer
    $timer = New-Object System.Windows.Forms.Timer
    $timer.Interval = Get-IntervalMs

    # Wire events
    $refreshButton.Add_Click({ Do-Refresh })
    $autoRefreshCheck.Add_CheckedChanged({ $intervalCombo.Enabled = $autoRefreshCheck.Checked; if ($autoRefreshCheck.Checked) { $timer.Interval = Get-IntervalMs; $timer.Start() } else { $timer.Stop() } })
    $intervalCombo.Add_SelectedIndexChanged({ $timer.Interval = Get-IntervalMs })
    $rangeCombo.Add_SelectedIndexChanged({ $custom = ($rangeCombo.SelectedItem -eq 'Custom'); $fromPicker.Enabled = $custom; $toPicker.Enabled = $custom; Do-Refresh })
    $listView.Add_SelectedIndexChanged({ Ensure-ControlsEnabled $true })
    $unlockButton.Add_Click({ Unlock-Selected })
    $resetButton.Add_Click({ Reset-SelectedPassword })
    $timer.Add_Tick({ Do-Refresh })

    Set-Variable -Scope Script -Name form -Value $form
    Set-Variable -Scope Script -Name refreshButton -Value $refreshButton
    Set-Variable -Scope Script -Name autoRefreshCheck -Value $autoRefreshCheck
    Set-Variable -Scope Script -Name intervalCombo -Value $intervalCombo
    Set-Variable -Scope Script -Name rangeCombo -Value $rangeCombo
    Set-Variable -Scope Script -Name fromPicker -Value $fromPicker
    Set-Variable -Scope Script -Name toPicker -Value $toPicker
    Set-Variable -Scope Script -Name listView -Value $listView
    Set-Variable -Scope Script -Name unlockButton -Value $unlockButton
    Set-Variable -Scope Script -Name resetButton -Value $resetButton
    Set-Variable -Scope Script -Name statusLabel -Value $statusLabel
    Set-Variable -Scope Script -Name timer -Value $timer
}

# Startup
Load-ModuleSafe
Initialize-UI
$form.Add_Shown({ Do-Refresh })
[void]$form.ShowDialog()


